const REDUX_ACTION_TYPE = {
    A1_PAGE_INCREASE: "A1_PAGE_INCREASE",
    A1_PAGE_DECREASE: "A1_PAGE_DECREASE",
    B1_PAGE_GET_DATA: "B1_PAGE_GET_DATA",
    B1_PAGE_GET_DATA_ERROR: "B1_PAGE_GET_DATA_ERROR",
}

module.exports = {
    REDUX_ACTION_TYPE: REDUX_ACTION_TYPE,
}